### ISSUE TITLE
new maintainer

### ISSUE THREAD

**Issue by djalmaaraujo** [linusg/spotifube#15]
@linusg I am very busy to continue this project. I would be happy to deliver mockups when it's needed, but I won't be able to code anymore.

Let's move this project to your account, shall we?

You are the most active and with the most experience at the moment to handle.

**Comment by djalmaaraujo** [comment]
@linusg Before I move, I wanna talk to you over email. is mail@linusgroh.de valid?

**Comment by sdhutchins** [comment]
@linusg I'm still working on stuff over here, and I still want to help. If you'd still like my help, please let me know. If not, please also let me know lol You can either let me know here or via email [sdhutchins@outlook.com](mailto:sdhutchins@outlook.com)

**Comment by linusg** [comment]
Hey of course I want! I even highly doubt that I will be able to efficiently work on this without a second person. I just wrote an email to @djalmaaraujo, let's wait for him. @sdhutchins you better push all your local work to a new branch to make the transfer as smooth as possible. (new repo url and such, the most straightforward way would be a new cloning of the repo :thinking:

**Comment by sdhutchins** [comment]
@linusg that's a great point. Might be best if I pushed to a new branch on this one before it was transferred to your account assuming that's the next step.

**Comment by linusg** [comment]
So he said just updating the remote origin address is fine, let's see. Still waiting for the second email, @djalmaaraujo :😉

**Comment by djalmaaraujo** [comment]
@linusg Repository transfer to linusg requested

**Comment by djalmaaraujo** [comment]
Just point your local remotes to another url. It's easier and clean.

**Comment by linusg** [comment]
... And accepted, even though it says it will probably take some minutes. I'll do my best.
@sdhutchins make sure to get it working properly, as I'll try. What do we start on working next?

**Comment by sdhutchins** [comment]
> ... And accepted, even though it says it will probably take some minutes. I'll do my best.
> @sdhutchins make sure to get it working properly, as I'll try. What do we start on working next?

I'm still finishing up #6 and #7 :see_no_evil:  lol @linusg
