### ISSUE TITLE
Create a bridge between the CLI and this project

### ISSUE THREAD

**Issue by djalmaaraujo** [linusg/spotifube#2]
Easiest way is using `spawn` from node. Let's see.

- [ ] Code a small internal library to handle spotify-downloader calls to the CLI and get the output

**Comment by sdhutchins** [comment]
> Talking about the CLI integration is important from the beginning on I think. For a quick start we should assume all required scripts and binaries are in $PATH. Next, we could work with this code:
> ```javascript
> const ChildProcess = require('child_process');
> 
> ChildProcess.exec('python3 -V', (err, stdout, stderr) => {
>   if (err)
>     console.error(err);
>   console.log(stdout);
>   // console.log(stderr);
> });
> ```

@linusg I'm going to try this out at home and see if I can get something simple working.

**Comment by djalmaaraujo** [comment]
This is done apparently, we already know how to do, so it's a matter of implementing.
