### ISSUE TITLE
Before starting: to be discussed, defining overall common plans

### ISSUE THREAD

**Issue by linusg** [linusg/spotifube#3]
To be discussed:
- Colors (imitate spotify? legal issues?)
- Techniques used: Electron, thus a web-tech based application with a JS "backend" and CSS frontend, I would directly start using Sass which I prefer over Less and directly written CSS for "larger" applications
- Usage workflow, related to mockups
- Any preferences to save? Is there something built into Electron for platform independent use?
- Keep dependencies low? IDK if there's any kind of helpers/utils for DOM manipulation etc. but in general I would stay away from stuff like jQuery.

**Comment by djalmaaraujo** [comment]
- Colors: We can use spotify pallet, they don't have rules about colors, only about their logo. https://developer.spotify.com/design/

- I am fine with Sass, though I think this app can be really simple, maybe we don't even need any pre-processor.

- OK

- Preferences maybe the folder to output.

```
bash
usage: spotdl.py [-h] (-s SONG | -l LIST | -p PLAYLIST | -u USERNAME) [-m]
                 [-nm] [-a] [-f FOLDER] [-v] [-i INPUT_EXT] [-o OUTPUT_EXT]
```

- We can use React+webpack and generate a single bundle for the front-end.

**Comment by linusg** [comment]
For reference, here are the colors used by spotify from down the page you've linked:

![grafik](https://user-images.githubusercontent.com/19366641/33025182-8bcde47a-ce0d-11e7-9576-e57d53368434.png)

**Comment by linusg** [comment]
Just to let you guys know, (_and I'm truly sorry that I don't know the female version of this term, please apologize! All my English is based on German secondary school English lessons_), I'm going to spend some times learning electron now.
- First of all, it's been on my wishlist for a long time now, including NodeJS.
- Second, I don't have to bother you @djalmaaraujo with things like "I have no clue about electron, can it do this and that?" anymore :smile: 
- Third, it would be a good thing for me before really starting here to have some best practices in terms of electron and node in mind.

Since I'm using HTML, CSS and JS on a daily basis, this won't take too long.

**Comment by djalmaaraujo** [comment]
@linusg Feel free to start the project. Let us just have some mockups before jumping into the code. Glad that you are working with electron now.

**Comment by sdhutchins** [comment]
@linusg Awesome! I'm also starting out with electron a bit. @djalmaaraujo Did you want to switch to electron-react-webpack or stick with the initial electron-webpack

**Comment by sdhutchins** [comment]
@linusg @djalmaaraujo I have an idea in my mind that I'm going to either draw or create on publisher as well if that's cool

**Comment by djalmaaraujo** [comment]
@sdhutchins create and paste some pics in #1

**Comment by djalmaaraujo** [comment]
I think the electron-webpack is very standard, we should stick with this. Also, I think react is in place already

**Comment by linusg** [comment]
As it seems like we're making progress very soon I ask you to please have a look at #5.

**Comment by djalmaaraujo** [comment]
Final goals:

MVP - First release:

An input text with a button where the user can paste a playlist link, see how many matches the link brought and download all the songs into a specific folder.
