### ISSUE TITLE
UI design discussion

### ISSUE THREAD

**Issue by linusg** [linusg/spotifube#4]
This thread can be used for discussion of UI and design features, I'll start with a few examples widgets:

https://code.linusgroh.de/spotify-ui.html

I tried to "reverse-engineer" some of the buttons and their behavior. Feel free to have a look at the sourcecode.

![ui](https://user-images.githubusercontent.com/19366641/33027054-5d1c577e-ce12-11e7-8ba9-b8b5d97ec0c0.gif)

**Comment by linusg** [comment]
...and now I realize I could have looked at the [Spotify Web Player](https://open.spotify.com) source code, which I did not but rather created the code from scratch. :thinking:

**Comment by linusg** [comment]
For reference, here's a collection of our mockups:

![mockup #1](https://user-images.githubusercontent.com/17803773/33291513-dfb5f21e-d3e7-11e7-9b09-234a7096a5bc.PNG)
----
![mockup #2.1](https://user-images.githubusercontent.com/3402/33293367-72969896-d3c4-11e7-9007-6fe40993e888.png)
![mockup #2.2](https://user-images.githubusercontent.com/3402/33293280-316c88c6-d3c4-11e7-91a3-73b83187586b.png)
![mockup #2.3](https://user-images.githubusercontent.com/3402/33293279-313e4de4-d3c4-11e7-87a1-a30936d3d3ce.png)
![mockup #2.4](https://user-images.githubusercontent.com/3402/33293281-319e3402-d3c4-11e7-8783-152f7c384590.png)
---
![mockup #3](https://user-images.githubusercontent.com/20976111/33295440-fe7280a2-d39a-11e7-9c14-56160781dbf7.png)

**Comment by linusg** [comment]
So, I have some great news:

- I have used `yarn` for some hours now, great experience so far. Sorry for the doubts @djalmaaraujo 
- I have cleaned up some of the default code, and would kindly ask you to keep some coding style rules in mind:
  - in HTML, even react, use double quotes
  - in JS, use single quotes
  - Put a semicolon in JS at the end of each statement/function call

To keep the codebase clean. :blush: 

Styling is mixed for now:
- Basic styles done in Sass directly
- Special styling done by applying classes:
  - Currently these:
  - `block`, `centered`
  - `full-width`
  - `bg-{light, dark, green}`
  - `fg-{light, dark, green}`
  - `p-{5, 10, 15, 20, 25, 30, 35, 40}`
  - `px-{5, 10, 15, 20, 25, 30, 35, 40}`
  - `py-{5, 10, 15, 20, 25, 30, 35, 40}`
  - `pt-{5, 10, 15, 20, 25, 30, 35, 40}`
  - `pb-{5, 10, 15, 20, 25, 30, 35, 40}`
  - `pl-{5, 10, 15, 20, 25, 30, 35, 40}`
  - `pr-{5, 10, 15, 20, 25, 30, 35, 40}`
  - and the same for margins

Spacing classes are obviously created by Sass :wink:

And this is the result so far:
![grafik](https://user-images.githubusercontent.com/19366641/33314683-b1d9676c-d42e-11e7-962d-95ef6c30e016.png)

**Comment by linusg** [comment]
Still a lot to do, next would be connecting the button to the backend, hiding the menu we don't need and a hell lot more.

**Comment by linusg** [comment]
And, to be discussed: should we have a fixed-size window like e.g. etcher has one or allow resizing?

**Comment by linusg** [comment]
Changed window title, menu is hidden now: https://github.com/djalmaaraujo/spotifube/commit/a74f21dc0b0badfaf05d40a44046acc9957d34d2

**Comment by djalmaaraujo** [comment]
@linusg  Awesome! Keep up the good work.

> Put a semicolon in JS at the end of each statement/function call

This is not needed, specially because we are using a bundler, that should improve the handle os missing semicolons. It also makes the code cleaner.

> And, to be discussed: should we have a fixed-size window like e.g. etcher has one or allow resizing?

Fixed with scrolling in side when we have a list of songs

**Comment by djalmaaraujo** [comment]
@linusg Did some changes. Let's do this. Open a Branch with your new changes, because it would be nice to have a decent review using PR's.

Leave a PR open with a `"WIP - something"` title and we keep reviewing.

I did some changes in the input and button size. 

BTW, if you are in germany, we can chat in the same timezone (almost). I am in portugal, -1hr from you only.

**Comment by djalmaaraujo** [comment]
I think we have enough for "design for the MVP". Let's have more issues focused on development.

**Comment by linusg** [comment]
> This is not needed, specially because we are using a bundler, that should improve the handle os missing semicolons. It also makes the code cleaner.

Seems to be arguably, since I think having a semicolon at each statement's end makes things more clear 😄 

> Leave a PR open with a "WIP - something" title and we keep reviewing.

Guess you mean future changes? And would you do the same? So we can review each other's changes, when it's not bugfixing or sth like that.

> I did some changes in the input and button size.

Now I feel like a screenshot or even GIF is important in a lot of cases - I'm still at work for one hour or two so I don't have the right setup to test, and even though I certainly understand the changes I can't really imaginge the final result. Except for a rough "different color and bg, more spacing"

> BTW, if you are in germany, we can chat in the same timezone (almost). I am in portugal, -1hr from you only.

YES! I find it rather annoying when I have to communicate with people being 8 hrs off and the conversation slows down a lot. (not communicating in general is annoying but the huge slow down if so)

**Comment by linusg** [comment]
> Fixed with scrolling in side when we have a list of songs

So, does this imply fixed height also? Would make sense IMO. A user could be confused if he just can size vertically...

I already made the `.container` having a vertical scrollbar explicitely when size is a problem: https://github.com/djalmaaraujo/spotifube/commit/9b2f095a5b4b8bbf7d53d1edb5cac461bb52e32d#diff-0528c6d0ead478be4b1668802ea2a171R18

**Comment by djalmaaraujo** [comment]
@linusg Yeah, I thought about 600 / 450, something close to this. You can pick something and we test later... for dev it's always better to have flexible

**Comment by linusg** [comment]
So, I'm not exactly happy about the new size. The color is fine, but it's way too big. So far I tried to roughly match the Spotify widgets, where the input is even smaller:
![grafik](https://user-images.githubusercontent.com/19366641/33336207-7d527b3c-d46f-11e7-9ea7-ff0a4ebe68d7.png)
But no, please let it be smaller as we're working on a regular desktop app.

What about this?
![grafik](https://user-images.githubusercontent.com/19366641/33336381-09904be2-d470-11e7-9bbb-10236ed7c29d.png)

![grafik](https://user-images.githubusercontent.com/19366641/33336369-fb78356a-d46f-11e7-97b2-9f7dfe13339f.png)

```
input[type=text] {
    border: none;
    padding: 12px 20px;
    border-radius: 20px;
    background: #282828;
    color: white;
    font-size: 14px;
}
```

Also I would like to reduce the space between the button and the input as they directly belong together.

**And, we all agree on making all the changes for at leas stage 0 and 1 as PR's, right?**

**Comment by linusg** [comment]
I'm open to constructive discussions, and expect many many changes and progress this evening and tomorrow, as I got plenty of time now. @sdhutchins, please give us any feedback on these UI related questions soon!

I'm currently working on a class representing the spodl.py Script, but am not exactly sure where to put it. We have access to the whole Node.js API even in the renderer, but it's not exactly renderer but does also not belong to main...
Thoughts?

**Comment by djalmaaraujo** [comment]
@linusg The letter-spacing 2px does not match spotify. Regarding the UI, Sizes... we don't need to match spotify identity (And I think it's bad for us if we do in terms of copyrights), we just need to FEEL LIKE spotify, because this is not an official app, and also, in terms of USER EXPERIENCE, the Input and the button are the most important pieces in the screen, so they should have a focus and a bigger size.

We are not replicating Spotify UI, remember this. The size of the spotify search is for search, this is for this application, not for search, got it?

Colors and radius are more nice to replicate, but don't feel like we should copy cat spotify. Also, let's focus on MVP process, delivering a good and working piece of app :)

We can always match styles/minimal sizes later.

**Comment by djalmaaraujo** [comment]
@linusg Thake a look at this app: https://pasteandplaylist.now.sh.

This is using not using the Spotify "ui" perfectly, but you can definitely know that this is related to spotify..

**Comment by djalmaaraujo** [comment]
> And, we all agree on making all the changes for at leas stage 0 and 1 as PR's, right?

Yeah, let's use PR's. Even if you have a OPEN PR for a lot of things, let's just try to make separated commits.

**Comment by linusg** [comment]
I get all of your points, and in no means I want to exactly match the UI of spotify, but the overall appearance should match. So I'm fine with changing colors and sizes, but still it's too big. And the 2px match the style, I've exactly tested using half-transparent windows. See the source, a font-size of 11px and a letter spacing of 0.16em results in 1.76px which rounds to 2px. See https://www.w3schools.com/TAGS/ref_pxtoemconversion.asp

If it would be this big, it would not match any of the desktop applications I know, thus not feeling native. More like "the user is almost blind, let's give him an input with the size native*3".

I'm certainly not ok with that.

**Comment by linusg** [comment]
I especially like the input from @zainimran's mockup, which looks far more harmonic. BTW the input is the only thing I highly criticize. The other UI elements are great, especially button and different font color and size for the number.

**Comment by djalmaaraujo** [comment]
Continue what you are doing, let's not have useless discussions about minor things.

Keep up the good work. It's going well

**Comment by djalmaaraujo** [comment]
*are

**Comment by djalmaaraujo** [comment]
@linusg https://github.com/djalmaaraujo/spotifube/projects/1
Let's use this to track our progress. ;)

**Comment by linusg** [comment]
Yup, I've seen it. Glad that we continue working on it! Also please see the update which I posted in the thread, I'm not quite sure how to deal with this right now.
