### ISSUE TITLE
Choosing a license

### ISSUE THREAD

**Issue by linusg** [linusg/spotifube#5]
Not *right* now, but hopefully as the first lines of code come in. The worst thing a dev can do is probably putting more than a couple of lines of code out there without stating any license.

I usually go for MIT but would really not mind if it's going to be some more restrictive or even less restrictive. [`spotify-downloader` is also licensed under MIT.](https://github.com/ritiek/spotify-downloader/blob/master/LICENSE.txt)

**Comment by djalmaaraujo** [comment]
@linusg MIT is good for me.

**Comment by djalmaaraujo** [comment]
Done.

https://github.com/djalmaaraujo/spotifube/blob/master/LICENSE
